### ISSUE TITLE
ㅁㄴㅇㄹ

### ISSUE THREAD

**Issue by kms0219kms** [int-Team/issue_room#4]
![image](https://user-images.githubusercontent.com/67222970/99350406-9ce5f180-28e1-11eb-8b25-d02935c5483d.png)

[이제 int는 좆된겁니다.](https://namu.wiki/w/X같은)

**Comment by chul0721** [comment]
> ![image](https://user-images.githubusercontent.com/67222970/99350406-9ce5f180-28e1-11eb-8b25-d02935c5483d.png)
> 
> [이제 int는 좆된겁니다.](https://namu.wiki/w/X%EA%B0%99%EC%9D%80)

이미 좆된 사람이 할말은 아님 ㄹㅇㅋㅋ

**Comment by chul0721** [comment]
밴 당해서 질질 짜네

**Comment by chul0721** [comment]
@kms0219kms
